package(
    default_visibility = ["//scripts:__pkg__"],
    licenses = ["notice"],
)

filegroup(
    name = "fusesoc_templates",
    srcs = glob(['fusesoc/*'])
)

filegroup(
    name = "agent_templates",
    srcs = glob(['agent/*'])
)

filegroup(
    name = "env_templates",
    srcs = glob(['env/*'])
)

filegroup(
    name = "bench_templates",
    srcs = glob(['bench/*'])
)
