load("@rules_hdl//verilog:defs.bzl", "verilog_library")

verilog_library(
    name = "prim_assert",
    hdrs = [
        "prim_assert.svh",
        "prim_assert_sec_cm.svh",
        "prim_assert_standard_macros.svh",
        "prim_flop_macros.svh"
    ],
    visibility = ["//visibility:public"],
)
