load("@rules_hdl//verilog:defs.bzl", "verilog_library")

verilog_library(
    name = "csr_utils",
    srcs = [
        "csr_utils_pkg.sv",
        "csr_seq_lib.sv",
    ],
    visibility = ["//visibility:public"],
)
